GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6108021df74b5a0a3474b629

###

POST  http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "This Person",
    "subscribedToChannel": "Some Youtube Channel"
}

###
DELETE http://localhost:3000/subscribers/6108021df74b5a0a3474b629

###
PATCH http://localhost:3000/subscribers/6108021df74b5a0a3474b629
Content-Type: application/json

{
    "name": "That Person"
}